# Generated by Django 3.0.5 on 2021-05-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Foodtype', models.CharField(max_length=4)),
                ('Foodsize', models.CharField(max_length=10)),
                ('Pizzaprice', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='add_new_menu',
            name='Foodsize',
        ),
        migrations.RemoveField(
            model_name='add_new_menu',
            name='Foodtype',
        ),
        migrations.RemoveField(
            model_name='add_new_menu',
            name='Pizzaprice',
        ),
    ]
