# Generated by Django 3.0.5 on 2021-05-10 17:35

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0002_auto_20210510_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuorder',
            name='Pizzaprice',
        ),
        migrations.AddField(
            model_name='menuorder',
            name='Pizzaorder',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuorder',
            name='Toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Cheese', 'Cheese'), ('Capsicum', 'Capsicum'), ('Jalapeno', 'Jalapeno')], default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
    ]
