# Generated by Django 3.0.5 on 2021-05-10 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0003_auto_20210510_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuorder',
            name='Pizzaorder',
        ),
    ]
