# Generated by Django 3.0.5 on 2021-05-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0005_remove_menuorder_toppings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuorder',
            name='Foodsize',
        ),
        migrations.RemoveField(
            model_name='menuorder',
            name='Foodtype',
        ),
    ]
