# Generated by Django 3.0.5 on 2021-05-10 17:57

from django.db import migrations
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0007_auto_20210510_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuorder',
            name='Toppings',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Cheese', 'Cheese'), ('Capsicum', 'Capsicum'), ('Jalapeno', 'Jalapeno')], default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
    ]
