# Generated by Django 3.0.5 on 2021-05-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0009_menuorder_pizzaorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuorder',
            name='Pizzaorder',
        ),
    ]
