# Generated by Django 3.0.5 on 2021-05-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub_part', '0011_auto_20210512_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registeration',
        ),
    ]
